name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Build Docker image
        run: docker build -t distributed-quicksort .

      # Future deployment step, commented out for now
      # - name: Push Docker image
      #   run: |
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #     docker tag distributed-quicksort my-docker-repo/distributed-quicksort:${{ github.sha }}
      #     docker push my-docker-repo/distributed-quicksort:${{ github.sha }}

  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install uv
          uv sync

      - name: Run tests
        run: uv run pytest

      - name: Run linters
        run: |
          uv run black --check .
          uv run ruff check
          uv run mypy .
