name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install uv
          uv build

      # Capture build artifacts from dist folder
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

      - name: Run application build
      - name: Verify build artifacts
        run: |
          if [ -z "$(ls -A dist 2>/dev/null)" ]; then
            echo "No build artifacts found in dist/"
            exit 1
          else
            echo "Build artifacts found in dist/"
          fi

  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install uv
          uv sync

      - name: Run tests
        run: uv run pytest

      - name: Run linters
        run: |
          uv run black --check .
          uv run ruff check
          uv run mypy .
